### ISSUE TITLE
Drush (composer) támogatás?

### ISSUE THREAD

**Issue by Endyl** [Pepita73/webproghu_dev#1]
Úgy látom, hogy a hivatalos [docker drupal][docker-drupal] alapján készült a docker setup, ami csak letölt egy adott verziójú drupal kiadást.

Ezzel csak annyi a probléma, hogy mivel 8.5.5 verzióval indulunk, így kizárjuk magunkat a Drupal parancssoros felületének a használatából (és sok automatizálási lehetőségből), mert a Drupal 8.4+ verzióját már csak a 9-es Drush [támogatja][drush-drupal-support], aminek a telepítéséhez viszont -ahogy az oldal elején írják- a Drupalt is composerrel kell telepíteni.

Találtam egy [írást][drupal-docker-composer], ami szintén a fenti docker drupal repót veszi alapul, de végül composerrel telepíti a Drupalt a Drush oldalán is javasolt [composeres setup][drupal-composer-project] segítségével.

Szerintem mi is csinálhatnánk hasonló módon, de ha már úgysem közvetlenül használjuk a [docker repót][docker-drupal], akkor például ki lehetne gyomlálni belőle a felesleges drupal kiadás letöltést, illetve beszervezni a composeres telepítést a Dockerfile-ba (ha nem robbantja fel a layer cache-t).

Mit gondoltok?

[docker-drupal]: https://hub.docker.com/_/drupal/
[drush-drupal-support]: http://docs.drush.org/en/master/install/#drupal-compatibility
[drupal-docker-composer]: https://circleci.com/blog/continuous-drupal-p1-maintaining-with-docker-git-composer/
[drupal-composer-project]: https://github.com/drupal-composer/drupal-project

**Comment by hunsly** [comment]
Én is észrevettem, hogy nincs Drush, ezért profile-al kezdtem megoldani. 4a76637

**Comment by Pepita73** [comment]
Elsőre én nem is találtam composeres telepítőt hozzá, úgyhogy mindenképp hasznosak a linkek.
Kérdés az, hogy mennyi fejlesztési időt ér meg nekünk, amit nyerünk vele.
Ismét hétvégén tudok pár órát rászánni.
Jelenlegi konténerben szerintem composer sincs (ha csak a forrás `php:7.2-apache` nem tartalmazza alapból), és biztosan nem 5 perc, viszont ha fontos feature így kimarad, akkor jobb lenne az elején rendezni.

**Comment by Endyl** [comment]
Ilyen [struktúrát](https://gist.github.com/Endyl/f3ab5e9f65e1c69b6dcc6ed9fbb4577b) generál a composeres megoldás. Van erre valakinek valamilyen értelmes COPY/volume layer ötlete?

A `composer install`-hoz szükség van ugyebár a `composer.json` és a `composer.lock` fájlokra, illetve a `src/scripts` tartalmára. Utána legenerálja gist-ben lévő `install-generated-files.txt` szerinti struktúrát.

Egyelőre eddig jutottam.

**Comment by Endyl** [comment]
Körbejárva a dolgot arra jutottam, mint a fenti cikk. Nincs értelme a Dockerfile-ban futtatni a `composer install`-t (úgy, hogy külön layer legyen belőle) és az egész src-t kéne mountolni.

Már csak azt nem tudom, hogy az entrypointot megcsináljuk-e úgy, hogy container indulásnál lefusson a `composer install`, vagy fapadosan, manuálisan kelljen megcsinálni egyelőre?

**Comment by Pepita73** [comment]
> az entrypointot megcsináljuk-e úgy

composer _install_ szerintem csak container _create_ - nél kell, tehát egy `RUN` sor a Dockerfile-ban.

Emellett jó lenne egy composer _update_ minden indulásnál (composer.json és / vagy composer.lock változott). Erre egyelőre nincs konkrét ötletem, de hétvégén végigmegyek [ezen a linkeden](https://circleci.com/blog/continuous-drupal-p1-maintaining-with-docker-git-composer/) én is.
Így első olvasatra nem vagyok meggyőződve arról, hogy _"Nincs értelme a Dockerfile-ban futtatni a composer install-t"_. De ki is kell próbáljam. Úgy tűnik, ő a Drupal forrását is verzióköveti, ami nekem nem tetszik. Viszont lehet benne pár jó ötlet.

@Endyl , lesz ebből PR-ed, vagy használjam fel a hasznos infóid és én csináljam? Szerintem jobb vonal a composer, ezért ez egy issue. :)

**Comment by Endyl** [comment]
Csináltam egy composeres setupot a [forkomban][fork] a [fork/i_1_composer][composer-branch] branchben.

Egyszer szükség van erre:

``` sh
docker exec -it drupal-apache sh -c "composer install"
```

miután elindultak a containerek (meg előtte a hálózatot még ugye be kell állítani, vagy megnézni a db IP-címét, mert az még #2-re vár).

Aztán mehet a telepítés :)

Ha ez bemerge-ölődik, az megoldja #5-öt is, aztán kitalálhatunk esetleg valami jobb megoldást is a volume-okra, meg rendezhetjük a settings fájlokat, stb. :)

[fork]: https://github.com/Endyl/webproghu_dev
[composer-branch]: https://github.com/Endyl/webproghu_dev/tree/fork/i_1_composer

**Comment by Pepita73** [comment]
`docker exec -it drupal-apache sh -c "composer install"`

Ezt nem lehet a Dockerfile végére betenni?
Mert ott már van oprendszer, php, apache. Mivel csak egyszer kell, ott lenne a helye, mert csak container create-kor fut.

**Comment by Pepita73** [comment]
Egyébként ránézésre nekem tökre tetszik. :)
Jó lenne mielőbb merge, holnap vagy vasárnap akkor elvinném #2 és a volume gondot, ha még fennáll a "jogi vita" (= írási jog).

**Comment by Endyl** [comment]
Mecsináltam a PR-t; jelenleg a környezet feláll két paranccsal (amiből az egyikre csak `clone`, vagy a composer fájljainak a módosítása után van szükség).

Az a probléma a composeres telepítésnek a docker image-be mozgatásával, hogy akkor a composerrel kapcsolatos műveletek (frissítés, új modul kipróbálása, stb) az image újraépítését tehetik szükségessé. Illetve nem tudom, hogy a volume-ok ebben a felállásban hogyan működnének.

Persze idővel lehet írni utility szkripteket, ha bonyolódnának a dolgok. Ekkor tényleg hasznos lenne, ha csak bash szkripteket kéne fenntartani és nem kéne PowerShell szkripteket is szinkronban tartani velük.

**Comment by Pepita73** [comment]
@Endyl , részemről tetszik, kipróbálnátok @inf3rno  val merge-ölést? (Szeretném, ha nélkülem is megoldott lenne.)
Most van egy kis dolgom, utána ebből kiindulva intézem a volume / db links dolgot.
Közben agyalok a composer install / update dolgon is, hogy lehetne a legkényelmesebb.
Szerintem az első (install) bemehet a konténer gyártásba, ez nem zárja ki a különálló (pl PowerShell) futtatását.
