### ISSUE TITLE
`settings.php` kezelése

### ISSUE THREAD

**Issue by Endyl** [Pepita73/webproghu_dev#13]
Véleményem szerint a `settings.php` publikus és a fejlesztői rendszerre vonatkozó részét nyugodtan kezelhetjük gittel (ezeket jelenleg ignorálja az alap composeres projekt `.gitignore`-ja). Az éles rendszerre vonatkozó beállításokat (adatbázis hozzáférés, one time loginokhoz használt salt, stb.) valahogy a deploy megoldásnak kéne vagy külön fájlként vagy a `settings.php` végéhez hozzáadva kitennie az éles rendszerre. (#12)

Ha #2 megoldódik, akkor azt is hozzá lehet venni a fejlesztői beállításokhoz.

**Comment by Pepita73** [comment]
Úgy néz ki, hogy kell is saját settings, de összevonva a src/.env - el. Egyelőre asszem megoldom másolással (post-install), ha valakinek lesz jobb ötlete, akkor code review-n, egyebütt jelezze plz.
Várjuk meg #2 -t, valószínű ott több minden is megoldódik.

**Comment by inf3rno** [comment]
@Pepita73 Ha nem túl nagy a különbség, akkor nem lenne jobb környezeti változóba betenni, aztán onnan berántani az éles szerveren? Persze nem nehéz a fájl csere vagy append sem, csak egy ötlet volt...

**Comment by Pepita73** [comment]
@inf3rno  see: https://github.com/Pepita73/webproghu_dev/pull/14
így db config már környezeti változóbol jön, hogy ezt deploy során / után honnan seteljük, azt rád bíznám. :)

**Comment by Pepita73** [comment]
@Endyl szerintem ez megoldva #14 - ben, ha egyetértesz, akkor ez is zárható.

**Comment by Pepita73** [comment]
@inf3rno nem, ezt így elqrtam, rosszkor másoltam ki a fájlt.
Erre PR-en mehetett volna rögtön change request, mert ez így tuti rossz.
Gyanítom, hogy a webes telepítés során írja hozzá a Drupal (nem tudom, miért).

Nice catch, köszi!

**Comment by Pepita73** [comment]
@inf3rno  Egyébként a második settings még onnan maradt benne, amikor csak a LINKS volt meg és weben meg kellett adnom a db kapcsolatot. Akkor írja a Drupal a fájl végére.
Tehát amikor megcsináltam a .env-es játékot, úgy csináltam a PR-t, hogy nem is tudtam róla, hogy nem az működik, hanem az előző webes setup. :-O
Most már a `src/web/sites/default/settings.php` végén sincs ott, pont azért, mert átlépi a webes telepítés során a beállítását.

@Endyl  szerintem ez zárható, ha megfelelőnek látod #14 - et.

**Comment by Pepita73** [comment]
Szerintem ezen már nincs megválaszolandó kérdés, és szerintem zárható #14 megoldja.
@Endyl , te issue-d... :)

**Comment by Endyl** [comment]
Megoldva #14-ben.
