### ISSUE TITLE
Adatbázis IP/host

### ISSUE THREAD

**Issue by Endyl** [Pepita73/webproghu_dev#2]
Ahogy az a README-ben is látható, többé-kevésbé random IP-t kap az adatbázis container, amit aztán a vonatkozó `settings.php` módosítgatásával kell korrigálni (ami macerás mind automatizálás, mind git-béli kerülgetés terén).

Mivel sem docker, sem hálózat "mágus" nem vagyok, bocsánat ha nem jó a megközelítés, de így hirtelen két ötletem támadt, amire találtam valamilyen megoldást:

- [statikus IP](https://stackoverflow.com/questions/27937185/assign-static-ip-to-docker-container#40573218)
- [hostname](https://stackoverflow.com/questions/29924843/how-do-i-set-hostname-in-docker-compose#47264089)

Az elsőre alapozva csináltam egy működő felállást, a másodikat még nem volt időm kipróbálni.

Van jobb megoldás? Ha nincs, a fentiek közül melyik a szerencsésebb?

**Comment by hunsly** [comment]
Igen, van: 4a76637 
settings.php és a docker-compose.yaml
Nekem így működött.

**Comment by Pepita73** [comment]
Gondoltam, hogy a links-el van bibi, ezért commenteltem ki. :)
Ki kéne próbálni, hogy:
```
    links:
      - db:localhost
```
vagy megfordítva, és akkor a configban localhost-ra lehet hivatkozni.
Az lenne a tuti szerintem.

**Comment by Endyl** [comment]
Közben olvasgattam még a témában, és a `links` elvileg már [deprecated/legacy][links-legacy], és helyette a [custom bridge][bridge-info] hálózatot ajánlják, ahol alapból látják egymást a containerek service név alapján ([compose infó][compose-network]). Itt is lehet [alias][compose-service-network]-t adni a service-nek hálózatonként, de szerintem nem lenne túl szerencsés így a `localhost` alias.

Ha lesz alkalmam, kipróbálom.

[links-legacy]: https://docs.docker.com/compose/compose-file/#links
[bridge-info]: https://docs.docker.com/network/bridge/
[compose-network]: https://docs.docker.com/compose/networking/#specify-custom-networks
[compose-service-network]: https://docs.docker.com/compose/compose-file/#networks

**Comment by hunsly** [comment]
A megoldásom miért is nem jó?

**Comment by Endyl** [comment]
Senki nem mondta, hogy nem jó; működik rendesen :) Csak miközben más témában olvasgattam a compose doksiját megakadt a szemem a nagy piros legacy figyelmeztetésen, így gondoltam megosztom itt az infót, hogy idővel kivehetik a dockerből, viszont van alternatíva.

Szóval felőlem nyugodtan csinálj egy PR-t, amiben csak az IP probléma megoldása van (akár linksszel, akár custom networkkel) aztán akkor zárható az issue. Bár lehet, hogy jobb lenne előbb merge-ölni #8-at, hogy minél előbb rendben legyenek az EOL-ok.

**Comment by Pepita73** [comment]
@hunsly , nyitott branch-en lévő megoldás még nem megoldás. Lehet bekerül, lehet nem.
Teljesen egyetértek Endyllel (kiemelés tőlem):

> csinálj egy PR-t, amiben **csak** az IP probléma megoldása van

Ha lehet, jó lenne inkább custom networkkel.

A config megoldása már másik issue-branch-PR szerintem, ott is érdemes lenne követni az eddig felmerült ötleteket (local vs all). Ezt meg kéne előzze a composer-es telepítés, hogy lássuk a könyvtárstruktúrát, jók legyenek a volume-ok.

**Comment by Pepita73** [comment]
Nem szép, de egyelőre maradt a LINKS + settings.php + bekerült egy .env.dev

**Comment by Pepita73** [comment]
Találtam egy egyszerű és jó példát network-re:

https://developer.okta.com/blog/2017/10/11/developers-guide-to-docker-part-3

**Comment by Endyl** [comment]
Jah, ilyenre gondoltam én is.

**Comment by Pepita73** [comment]
Fontos, hogy mindenkinek uptodate Docker legyen, mert én hamar beszoptam a network option-öket.
Most nálam Version 17.09.0-ce-win33 (13620) van, szeretne update-elni 18.x-re, de nem engedem, mert 2/2 meghalás volt update során.
Jelenleg viszont ezzel jól műxik a "custom default network". (Menet közben találtam, hogy ez kb ugyanaz, mint a régi `network_mode: bridge` + `links:`, csak most már lehet többet is megadni. Ha default a neve, akkor nem kell megadni a service-eknél, alapból azt fogják használni.

Custom driver-be én nem szeretnék belemenni soha, az már nagyon rendszergizda feladat. :)
