### ISSUE TITLE
develop branch

### ISSUE THREAD

**Issue by Endyl** [Pepita73/webproghu_dev#20]
#17 alapján létre kell hozni a `develop` branchet, és beállítani a `Settings > Branches` részen egy szabályt, hogy oda is kelljen PR és legalább 1 review. Meg az új commit utáni review elavulást is be lehet állítani szerintem.

@Pepita73: neked adtam, mert a beállításokhoz csak te férsz hozzá.

**Comment by Pepita73** [comment]
ok pár óra múlva csinálom

**Comment by Pepita73** [comment]
Jelenleg ez van, a két rule egyforma (csak az 1 db review van bepipálva)
![image](https://user-images.githubusercontent.com/3989431/43848984-885497f4-9b34-11e8-928a-934a8fb2231d.png)

**Comment by Pepita73** [comment]
Kérdés: mit jelent a github-on a default branch?
Ha ugyanazt, mint gitLAB-on, akkor ez egy kicsit kényelmetlen / odafigyelős lesz itt is.
Mert a default-ból szeretné létrehozni a gyorsmenüben:
![image](https://user-images.githubusercontent.com/3989431/43849112-ec90beaa-9b34-11e8-9ba4-12a027cec452.png)

Rá kell állni előbb a develop-ra, utána ajánlja abból az újat. Erre figyelni kell, bár elvileg sok bajunk nem lesz véletlenszerű master -> develop merge-ből, legfeljebb ha hotfix-nél elfelejtettük, akkor így pótlodik.
De ha van valami jó trükk erre, osszuk meg.

**Comment by Pepita73** [comment]
Bocsi, most néztem, hogy kell az elavulás is, szóval most ilyen mindkettő:
![image](https://user-images.githubusercontent.com/3989431/43849518-eed9630a-9b35-11e8-8e83-6e7347949880.png)

**Comment by Endyl** [comment]
Nem kell githubon branchet készíteni :D

Ezért [mondtam](https://github.com/Pepita73/webproghu_dev/issues/17#issuecomment-411348028) a git flow szerű eszközöket, mert azok elvileg megoldják a megfelelő helyről történő leágazást és a megfelelő helyre történő merge-ölést.

**Comment by Pepita73** [comment]
@Endyl , kérlek check után zárd le, ha megfelel.

**Comment by Pepita73** [comment]
Hááát én inkább szeretem a parancssort, illetve 1-2 sűrűn előforduló több parancsos műveletre vagy feledékenység ellen a bash scriptet. :)

**Comment by Endyl** [comment]
A git flow parancssoros cucc :)

**Comment by ghost** [comment]
@Endyl Itt mi volt a dokumentálandó információ? Lehet csak véletlenül lett doc needed?

**Comment by Endyl** [comment]
Szerintem az, hogy mi, honnan ágazik le és hova tér vissza. Az meg benne van a branching megtárgyalásában és a wikiben is. Leveszem róla, és szerintem documented sem kell rá.
