### ISSUE TITLE
Issue címkék dokumentálása

### ISSUE THREAD

**Issue by Endyl** [Pepita73/webproghu_dev#23]
Dokumentálandó issue(k):

- #19

Dokumentáció helye(i):

- [Issue címkék](https://github.com/Pepita73/webproghu_dev/wiki/Issue-c%C3%ADmk%C3%A9k)

**Comment by Endyl** [comment]
Valaki nézzen rá, hogy kihagytam-e valamit :)

**Comment by ghost** [comment]
@Endyl Szerintem rendben van, zárhatod.

**Comment by ghost** [comment]
Vagy ilyenkor zárja le a reviewer?

**Comment by Endyl** [comment]
Szerintem zárhatja.

**Comment by ghost** [comment]
Ok.
