### ISSUE TITLE
Milyen adatokkal történjen a regisztráció?

### ISSUE THREAD

**Issue by ghost** [Pepita73/webproghu_dev#25]
Volt erről is szó #22 -nél, hogy hogyan történjen a regisztráció. Felvetődött, hogy csak github account-al lehessen regisztrálni, vagy esetleg email cím, jelszó párral, esetleg mindkettővel. Jó lenne ezt átbeszélni, hogy lehessen dolgozni rajta.

**Comment by ghost** [comment]
A #24 -et esetleg ez blokkolhatja, mert ha úgy döntünk, hogy csak github account mehet, akkor a captcha elképzelhető, hogy szükségtelenné válik. Kitegyem rá a blocked statust?

**Comment by Pepita73** [comment]
Első körben én arra szavazok, hogy csak _hagyományos_ (email, jelszó, captcha) regisztráció legyen, a github-os _belépés_ egy plusz feature, és ráér később is.
Fontosabbnak tartom az elindulást.

Github-os _belépés_ felvet GDPR kérdést is: úgy kell megoldani, hogy emiatt nálunk ne legyen személyes adat tárolva, még név sem. Ehhez végig kell nyálazni az adott modult. 
Jó dolog az, ha be lehet lépni githubbal, de ez authentikáció, ami önmagában nem teszi lehetővé az adattárolást / kezelést. Ahhoz (is) külön elfogadó nyilatkozat kell, és az a login feature, ami több lépésből áll, mint a regelt useré - hááát szerintem nem lenne sűrűn használatban.

**Comment by Pepita73** [comment]
Ja, és az adatok:

- Teljes név (ha nem akarja megadni, potenciális szájkaratés, mint láttunk WL-en is párat)
- email
- Általa választott felhasználónév (ami még nem volt), ezt meg kéne nézni, hogy még mindig bementi-e Drupal a comments, stb táblákba string-ként. Ha igen: külön fel kell rá hívni a figyelmet, hogy soha nem fogjuk törölni, változtatni.

Más adatot én nem kérnék. Lehet esetleg opcionálisan telefon / skype / egyéb, de nekünk, adatkezelőnek az a jobb, ha minél kevesebb. Adja meg emailen (privát üzenet) annak, akinek akarja.

**Comment by Endyl** [comment]
> az a login feature, ami több lépésből áll, mint a regelt useré - hááát szerintem nem lenne sűrűn használatban

Hogy áll több lépésből? Regisztrációnál nem kell új jelszót kitalálnom (max belépni githubon, de ha ez korábban megvan, akkor csak két kattintás a regisztráció), loginnál meg ugyanúgy csak kattintok a linkre, és ha be vagyok lépve githubon, akkor kész, egyébként meg ugyanazt csinálom, mint a sima oldalon tenném. Szóval rossz esetben ugyanannyi, jó esetben kevesebb lépés szerintem.

De ha "jogilag" macerás, akkor maradhatunk a jelszónál.

Amúgy miért kell külön teljes név, meg nick? Van egy username, aztán aki reklámozni akarja az IRL identitását, az teljes nevével regisztrál, aki meg nem, az választ egy sima nicket. Én is, ahol lehet, nem adom meg a teljes nevem, mert a többségre nem tartozik; mégsem trollkodni járok oldalakra :)

**Comment by Endyl** [comment]
Az egyéb adatoknak meg lehet egy opcionális "bemutatkozás" mező, ahol mindenki vérmérséklete alapján dox-olhatja magát :D

**Comment by ghost** [comment]
Engem érdekelne, hogy a GDPR hogyan áll ezekhez? Valami olyasmi rémlik, hogy biztosítani kell lehetőséget a személyes adatok megváltoztatására, illetve ha elkérünk személyes adatokat akkor indokolni kell, hogy miért. A nick vajon személyes adatnak minősül? Ha igen, akkor ha konstans, akkor csak account törléssel lehet eltüntetni. A másik, hogy ha teljes nevet kérünk, akkor gondolom indokolni kell azt is, hogy miért kell. Szerintem is felesleges egyébként, főleg ha arra törekszünk, hogy minél kevesebb személyes adat legyen.

A személyes adatokat egyébként titkosítottan kell tárolni, vagy ez most nem szempont? Ha igen, akkor muszáj modult írni ehhez is Drupal-hoz, mert a jelszavas megoldásuk után kétlem, hogy figyelnének ilyesmire. Ez valszeg annyira megbonyolítaná a projektet pl kereshetőség, cache-elés, stb. szempontból, hogy egyelőre jobb elvetni... Remélhetőleg a GDPR nem teszi kötelezővé.

Jól értem akkor, hogy abban megegyeztünk, hogy lesz jelszavas regisztráció captcha-val, és a github-os csak extra, ami később esetleg implementálva lesz, vagy erről még folyik a vita? Ha igen, akkor jó lenne előnyök - hátrányok listákat készíteni, hogy haladjunk.

**Comment by Endyl** [comment]
- Jelszó
  - előny:
    - beépített feature
    - GDPR szempontból egyszerűbb?
  - hátrány:
    - felhasználóknak ki kell találniuk a regisztrációhoz
    - a megfelelő tárolásról gondoskodni kell, lásd: #21
- SSO
  - előny:
    - jobbára egyszerűbb login/regisztrációs élmény
    - az SSO provider oldja meg helyettünk loginra/regisztrációra a bot szűrést
  - hátrány:
    - modult kell telepíteni, beállítani
    - nem biztos, hogy mindenkinek van pl. github fiókja
    - github api tokent kell beszerezni (gondolom nem bonyolult, csak ki kell találni, hogy milyen github accounttal igényeljük)

Számomra mindegy. Úgy néztem, később is be lehet vezetni az SSO-t, és aki akar, át tud térni rá.

**Comment by Pepita73** [comment]
> Az egyéb adatoknak meg lehet egy opcionális "bemutatkozás" mező, ahol mindenki vérmérséklete alapján dox-olhatja magát :D

Ez rossz ötlet, mert üzemeltető ként ugyanúgy felelsz az ott megadott személyes adatokért, kivéve, ha odaírod a mező mellé, hogy ott tilos személyes adatot megadni, mert nem felelünk érte.
A github - os reg : el kell dönteni, hogy ez reg VAGY csak login.
Utóbbi esetben semmi személyes adatot nem szabad kezelni, még email sem.
Különben minden egyes login folyamat része a tájékoztatás kirakása és elfogadás. 
Ez a sok klikk.

Ha github account regisztráció van, akkor megússza egyszer ezt, de minden egyes adathoz tárolási engedélye kell.

Üdvözlettel:
Horváth Péter

(Mobilról)

**Comment by Pepita73** [comment]
GDPR gondot azért vállaltam, mert nálunk volt oktatás hozzá, plusz ha szükséges, tudok szerezni kis support ot. 
Ami csak érdekel, az menjen szerintem egy low priority issue ba.
Indokolni kell igen, amit meg is tettem. 
Username nem személyes adat, csak ha azt kéred, hogy pl "olyat adj meg, amiről felismernek a barátaid". Ha az ellenkezőjét kéred, máris nem az... :) 
Az, hogy ő végül mit ad meg, ő dolga. 
Bocs, mobilról nem tudom jobban. 

Nem kell titkosítva tárolni, viszont nem szabad feleslegesen sem (life cycle).
Azt is ki kell írni, meddig kell. 
Persze minden vállalható dolgot meg kell tenni a biztonságért, és ha esemény van, jelenteni NAIH nak.


Üdvözlettel:
Horváth Péter

(Mobilról)

**Comment by Endyl** [comment]
> Ez rossz ötlet, mert üzemeltető ként ugyanúgy felelsz az ott megadott személyes adatokért, kivéve, ha odaírod a mező mellé, hogy ott tilos személyes adatot megadni, mert nem felelünk érte.

Nem egészen értem, hogy egy bemutatkozás mező miben különbözik például egy hozzászólástól. Mindkettőben akkor ad meg személyes adatok valaki, amikor csak akar. De ha az kell a GDPR-nak, hogy odaírjuk alá, hogy "ne írj bele személyes adatot, mert nem felelünk érte", akkor odaírjuk :) Igazából erre gondoltam az önmaga doxolásánál.

> A github - os reg : el kell dönteni, hogy ez reg VAGY csak login. Utóbbi esetben semmi személyes adatot nem szabad kezelni, még email sem. Különben minden egyes login folyamat része a tájékoztatás kirakása és elfogadás.  Ez a sok klikk.

Szerintem ezt sem értem. Főleg azt, hogy miért kéne minden belépéshez GDPR jóváhagyás. Aki githubbal akar belépni, az vagy eleve githubos accounttal regisztrál, vagy ha később tér át rá, akkor belépés után össze kell kötnie a két accountot, és mondjuk elfelejtjük a jelszavát. De a folyamat lényegében mindig az, hogy átirányítjuk githubhoz, ott ha engedélyezi a hozzáférést, akkor a github megoszt velünk valamilyen adatot, ami alapján tudjuk azonosítani, hogy milyen felhasználóról van szó (nem tudom, hogy ez email-e, vagy csak a github usernév) és ez alapján indul a session.

**Comment by ghost** [comment]
@Endyl 
A saját tájékoztatót esetleg helyettesíti az, hogy a github feldobja a kérdést, hogy megosztja e velünk az email címét és a nevét, vagy muszáj nekünk is erre valami külön adatvédelmi nyilatkozatot, checkbox-ot, meg minden francot kitenni? Facebook alkalmazásoknál azt hiszem nem jött fel külön tájékoztató ebből a célból... De mondjuk már régen telepítettem facebook appot, lehet, hogy meg kéne nézni, hogy most milyen.

**Comment by Endyl** [comment]
Szertintem ha tárolunk valamilyen személyes adatot, akkor a mi oldalunkon is kell jóváhagyás. Úgy gondolom, ilyen téren username és email ami játszhat, meg esetleg github név, ha az annak számít. Nem hiszem, hogy mást nagyon kellene tárolnunk. De a usernamenek sem kérném "kötelezően" a teljes nevet.

**Comment by ghost** [comment]
@Endyl 
Akkor valahogy úgy kéne, hogy rávisz egy regisztrációs űrlapra, amit kitölt a github adatok alapján, és gondolom az email readonly vagy disabled lesz, hogy abba már ne tudjon beleírni, a többin meg változtathat, ha pl nick név ütközés van, vagy ilyesmi. Aztán checkbox az adatvédelemre, és mehet az űrlap, mert gondolom captcha erre nem fog kelleni. Stimmel nagyjából? Ilyenkor egyébként kell generálni jelszót az illetőnek, vagy feltételezzük, hogy úgyis mindig a github accountjával fog belépni? Ha igen, akkor a Drupal-ba vajon lehet felvinni üres jelszóval user-t?

Én az eddigiek alapján úgy látom, hogy max a jelszó tárolást spórolnánk meg azzal, ha csak githubos regisztráció és beléptetést lenne, de talán még azt sem. Szóval én mindkét féle regisztrációra és beléptetésre szavazok.

**Comment by Endyl** [comment]
Ha igaz, amit [ennél a modulnál][social-login] írnak, akkor még GDPR nyilatkozatról is gondoskodnak (bár gondolom, minimum le kell fordítani vagy meg kell írni a szövegét; remélhetőleg van lehetőség ennek a beállítására, meg hogy csak bizonyos szolgáltatásokat engedélyezzünk). Ki kellene majd próbálni, ha szeretnénk ilyet.

[social-login]: https://www.drupal.org/project/social_login

**Comment by ghost** [comment]
@Endyl Ha van rá kész modul, akkor szívesen lefordítom. CMS-ekben általában szokott lenni multilang modul is, aztán nyelvi fájlokat kell csinálni hozzá, nem egy nagy kunszt, feltéve, hogy multilang-ra csinálta a fejlesztője a beléptetőt. Ha nem, akkor muszáj lesz beleírni. Ezeket a modulokat egyébként composerből is be lehet rántani valahogyan, vagy muszáj letöltögetni és kézzel hozzátákolni? Valami olyasmi rémlik, hogy CMS-eknél szokott erre lenni külön extension-ös oldal, ahol a user 1 tudja telepíteni őket. Jó lenne ezt elkerülni és kódból telepíteni ha lehet.

**Comment by Endyl** [comment]
Van a drupalban felület fordításra (meg úgy emlékszem import/export is van, ha valaki poedittel vagy hasonlóval szeret dolgozni), ha normálisan írták meg a modult. Vagy lehet, hogy eleve cserélhetőre írták meg a megjelenő üzeneteket.

Én úgy tudom, hogy drupal.org-on lévő modulokat lehet telepíteni composerrel. De ha le kell tölteni (vagy saját modul), akkor is meg lehet oldani elvileg kódból.

**Comment by ghost** [comment]
@Endyl Oké. Akkor kelleni fog egy tracking issue, amivel a regisztrációs rész fejlesztését követjük. Ugye bele kell tenni a captcha-t a jelszavas változatba is, meg kell checkbox gondolom az adatvédelmi nyilatkozatnak is.

**Comment by Endyl** [comment]
Jah, lehet egy regisztráció tracking. Hogy milyen checkbox kell és hova, azt majd @Pepita73 megszakérti gondolom :)

**Comment by ghost** [comment]
Csináltam egy kezdetleges tracking-et: #33 , írjátok majd át, ahogy jónak látjátok. Egyelőre ezt még nem lehet bezárni a GDPR-es task miatt, amit Pepita felvett. Igyekszem a teszt rendszerrel, hogy már tudjuk használni a regisztráció teszteléséhez, úgyhogy most a hétvégére kiszállok az issue nézegetésből, vagy legalábbis nem nézek rá annyira gyakran.

**Comment by Pepita73** [comment]
Nem csak a tárolás érdekes GDPR miatt, hanem mindenféle adatkezelés. 
Tehát ha csak "röptében" ki írod egy kizárólag admin usernek az ő személyes adatát, az már nyilatkozat köteles. Semmit nem tároltál, de egy másik személy / alkalmazás "látta".
Ezt nem tudja és nem is kezelheti a github helyetted. 
Ezért is nagy különbség a reg és a login.
A username elvileg nem személyes adat, de csak önmagában. 
Ha társul hozzá más is, akkor necces. 
Username = anonym azonosító. Ha nem profilozol  (User követő, stb), akkor önmagában lehet használni, elég a github engedély. 
Egyébként az egész github login / reg azért is bőven rá ér, mert ha csak az lenne, akkor csomó felhasználót buknánk. 
Vagyis a "sima" reg mindenképp kell, a github lehet egy plusz lehetőség. 


Üdvözlettel:
Horváth Péter

(Mobilról)

**Comment by Pepita73** [comment]
Talán holnap "megszakértem" , de megyünk családdal mindenfelé, szóval nem biztos... :) (laptop lesz nálam, amin docker még nincs)

Üdvözlettel:
Horváth Péter

(Mobilról)

**Comment by ghost** [comment]
@Pepita73 
Oké. Én utólagos engedelmeddel kiveszem erről a checkbox-ot, és folytassuk a tracking-en ezt a szálat. Oda is bekerült egy GDPR-es checkbox, ahol majd ki kell fejteni, hogy mi legyen a nyilatkozatban.
