### ISSUE TITLE
git flow setup script

### ISSUE THREAD

**Issue by Endyl** [Pepita73/webproghu_dev#26]
A git flownak van pár konfigurációs beállítása, amit nem lehet `git clone`-nal a kliensre juttatni (a `.git/config` fájlból olvassák fel ezeket a beállításokat; valamiért az a filozófiájuk, hogy a git flow az egyes repositorykra vonatkozik, nem pedig a kódbázisra).

Ezért azok számára, akik a git flowt szeretnék a branchek kezelésére használni, célszerű egy scriptet készíteni, ami elvégzi a megfelelő beállításokat (egyelőre csak branch nevek és prefixek beállítására van szükség), hogy elkerüljük az esetleges elírásokból fakadó következetlenségeket.

---

Branch: [i-26-git-flow-setup](https://github.com/Pepita73/webproghu_dev/tree/i-26-git-flow-setup)

**Comment by ghost** [comment]
Nagyon jó ötlet. Szerintem is oltári nagy baromság a .git mappában kézzel turkálni, mert az ignorálva van. Nem is értem eddig miért nem jutott eszembe, hogy scripttel csináljam.

**Comment by Endyl** [comment]
Kézzel mondjuk nem kéne matatni `.git/config`-ban, mert van a git flownak init scriptje. Az init script viszont igényel kézzel írt válaszokat, mert nem mindenhol az alapbeállításokat használjuk. Az ottani elírásokat akarom kiküszöbölni ezzel a scripttel.

**Comment by ghost** [comment]
@Endyl Igy hirtelen csak annyit találtam, hogy a `git flow init -d` után `git flow config ...` -ot szokás futtatni, amiben átállíthatóak a default értékek. Igy nem kell kézzel beütni semmit és egyedi megoldás sem fog kelleni a config átírására. (Ami ugye jó, mert nem törik, ha változik a git flow, bár úgysem fog...)

**Comment by Endyl** [comment]
Tudom; csak az "ügyvitel" miatt hoztam létre az issuet :)

**Comment by ghost** [comment]
@Endyl Ja ok, csak próbáltam segíteni. :-)

**Comment by Endyl** [comment]
Tudom, és köszi! :)

Ugyanakkor ezért van a *"Tag: question"*, hogy tudjuk, mikor kell az időnket segítségre fordítani, és adott esetben ne végezzük el ugyanazt a "munkát" többen. De nem zavar, hogy írtál, csak mondom, hogy ha időt akarsz spórolni magadnak, akkor nem muszáj az ilyeneknek utánanézni; persze ha érdekel valami, akkor nyugodtan :)

**Comment by ghost** [comment]
Én ennek a review-ját @Pepita73 -ra bíznám.

**Comment by Pepita73** [comment]
Bocsi, majd holnap, tereske tavon vagyok. :)

Üdvözlettel:
Horváth Péter

(Mobilról)

**Comment by Pepita73** [comment]
Fixed-et döntsd el @Endyl , kód szinten szerintem nagyon jó, van kérdésem:

```bash
Pepita@PEPITA-HOME MINGW64 ~/Containers/webproghu_dev (i-26-git-flow-setup)
$ git flow feature start test1
Switched to a new branch 'i-test1'

Summary of actions:
- A new branch 'i-test1' was created, based on 'develop'
- You are now on branch 'i-test1'

Now, start committing on your feature. When done, use:

     git flow feature finish test1


Pepita@PEPITA-HOME MINGW64 ~/Containers/webproghu_dev (i-test1)
$  git flow feature finish test1
Switched to branch 'develop'
Your branch is up-to-date with 'origin/develop'.
Already up-to-date.
Deleted branch i-test1 (was ec4c121).

Summary of actions:
- The feature branch 'i-test1' was merged into 'develop'
- Feature branch 'i-test1' has been locally deleted
- You are now on branch 'develop'


Pepita@PEPITA-HOME MINGW64 ~/Containers/webproghu_dev (develop)
```

1. Lehet-e esetleg tiltani a `git flow feature finish` parancsot? Mert helyből merge develop-ba, amit nem szeretnénk.

2. Ezt szerintem ki kéne hangsúlyozni wikiben, hogy _csak_ PR-en keresztül mehet bármi develop-ba. (Fenti példán nekem úgy tűnik, hogy simán betolta, mondjuk nem volt kód-módosítás, talán ezért nem látszik githubon.)

3. `e-pepita-honaljpumpas-szemuvegdaralo` kísérleti branch-et hogy lehet létrehozni vele? Lehet, hogy jó lenne ennek külön wiki, mert amúgy tök jó cucc, viszont ezt is tudni kell használni.

**Comment by Endyl** [comment]
Szerintem ezek jobbára le vannak írva [itt](https://github.com/Pepita73/webproghu_dev/wiki/Branching-modell) és [itt](https://github.com/Pepita73/webproghu_dev/wiki/Branchek-kezel%C3%A9se).

Az, hogy lefut a merge a helyi repódban, nem jelent semmit. Pusholni elvileg nem kéne tudnod githubra. Az lehet, hogy ezt hangsúlyosabban meg kéne említeni a branchek kezelésénél.

Az lenne a jó, ha a `git flow` integrálná a [hub](https://github.com/github/hub)ot is, és akkor mondjuk a `finish`-hez be lehetne állítani, hogy pull requestet készítsen.

**Comment by Pepita73** [comment]
@Endyl igen, szerintem[ itt kellene említeni](https://github.com/Pepita73/webproghu_dev/wiki/Branchek-kezel%C3%A9se#issue-n-v%C3%A9gzett-munka-befejez%C3%A9se), hogy ezt már felületen kell végezni.

Az `e-pepita-honaljpumpas-szemuvegdaralo` kísérleti branch-re nem találtam (git flow) példát. Ha azt kézzel kell, akkor valahogy szerintem azt is jelezni kéne a wikin.

Ezek viszont már csak a wikit érint(het)ik, a PR szerintem merge-elhető.

**Comment by Pepita73** [comment]
(Légyszi valaki nyomja meg a merge gombot, hogy tudjam biztosan, hogy más is tudja.. :-D )

**Comment by Endyl** [comment]
A kísérleti branch szerintem elég egyértelműen le van írva:

> **Kísérleti** branch esetén `develop`-ról, vagy másik issue branchről ágazunk le, `e-{user}-{rovid-leiras}` névvel. Ennek nincs git flow megfelelője.

Ha valahogy máshogy szeretnéd megemlíteni, akkor nyugodtan szerkeszd szerintem.

Írtam egy egyértelműsítő bekezdést a `finish` parancsokról, és rányomtam a merge-re is :)
