### ISSUE TITLE
Branching dokumentálása

### ISSUE THREAD

**Issue by Endyl** [Pepita73/webproghu_dev#27]
Dokumentálandó issue(k):

- #17

Dokumentáció helye(i):

- [Branching modell](https://github.com/Pepita73/webproghu_dev/wiki/Branching-modell)

**Comment by ghost** [comment]
@Endyl 

Bár nem túl jelentős, de kimaradt, hogy dash-case-t használunk a változóknál az issue neveknél, nem pedig pl camel-case-t. Ezt akár egy példával is bele lehet írni, pl: `i-26-git-flow-setup`, nem pedig `i-26-gitFlowSetup`, csak hogy biztosan egységes legyen.

A release branch-nek mi lenne az előnye? Jól gondolom, hogy csak annyi, hogy elhalaszthatjuk a release-t, amíg még egyszer átnézzük, hogy nincs e benne valami hiba, és közben fejleszthetünk tovább a dev-en a következő release-re? Ha így van, akkor a release-re is mennek majd hotfix-ek?

**Comment by Endyl** [comment]
Jah, jó ötlet beleírni a dash-case-t.

A release branchnek meg valóban az a célja, hogy az utolsó simítások ne tartsák fel az új verzió fejlesztését. Hotfix csak masterre kell szerintem; egy még nem éles változatnál nem kell "kapkodni" :D

Az eredeti blogbejegyzésben sima commitok vannak a release branchen; szerintem mi csinálhatunk onnan is issue brancheket.

Egyébként a git flowban vannak feature és bugfix branchek is, de csak névben különböznek, mindkettő a developból származik alapból, úgyhogy szerintem nyugodtan egy kalap alá vehetjük őket issue branchként.

**Comment by Endyl** [comment]
[Voilà!](https://github.com/Pepita73/webproghu_dev/wiki/Branching-modell)

**Comment by ghost** [comment]
Szerintem rendben van, lezárom.
