### ISSUE TITLE
Mik legyenek a milestone-ok?

### ISSUE THREAD

**Issue by ghost** [Pepita73/webproghu_dev#28]
Jó lenne hozzárendelni milestone-okhoz az issue-kat, mert nehéz prioritást meghatározni, ha nem tudjuk, hogy mi a milestone (ugye p2 milestone blokkolóként van meghatározva). Ezen kívül lehet, hogy én siklottam át felette, de úgy emlékszem nem beszéltük meg, hogy 1 milestone : 1 release a model, amit követünk, vagy neadjisten független a két dolog egymástól, és valahogy máshogy követjük, hogy kész vagyunk e release-re. Ez gondolom a #27 -t is valamennyire érinti.

**Comment by Endyl** [comment]
Az biztos hogy release-eknek kellene milestone; szóval kezdhetünk mondjuk egy `v1.0.0` milestone-nal.

Ha lehet milestone-okat egymás alá rendelni, akkor a későbbiekben lehetnek milestone-ok nagyobb feature-ök is. Egyébként maradjon csak release a milestone, az egyebek meg majd csoportosulnak tracking issuek alatt.

**Comment by ghost** [comment]
Oké, akkor gondolom ezt is le kell dokumentálni, aztán le lehet zárni ezt a részét a workflow-nak.

**Comment by ghost** [comment]
Ilyenkor ha doc needed, akkor le lehet zárni, vagy várjuk meg, amíg elkészül? Van olyan szabály, hogy lezárt issue-hoz nem nyúlunk pl label-ek terén, csak nyitotthoz?

**Comment by Endyl** [comment]
Szerintem mehet lezártba, ha van doksis issue.

Rendtartás kedvéért szerintem simán hozzá lehet nyúlni lezárt issuekhoz is.

**Comment by ghost** [comment]
@Endyl 
Oké, akkor majd le kell venni róla a doc needed flag-et, ha megvan a dokumentáció.
