### ISSUE TITLE
Milestones dokumentálása

### ISSUE THREAD

**Issue by ghost** [Pepita73/webproghu_dev#29]
#28 alapján

**Comment by ghost** [comment]
Kérdés ezzel kapcsolatban, hogy esetleg mehetne e a branching egy részeként (ha tényleg használjuk a release branch-eket), vagy külön page kell neki?

**Comment by Endyl** [comment]
Egyelőre berakom oda; ha részletezni kellene jobban, akkor majd lesz másik issue.

**Comment by Endyl** [comment]
[Vonatkozó rész](https://github.com/Pepita73/webproghu_dev/wiki/Branching-modell#milestone-ok)
