### ISSUE TITLE
Tárhely kérdése

### ISSUE THREAD

**Issue by ghost** [Pepita73/webproghu_dev#30]
Jó lenne dönteni a tárhelyről, hogy hol legyen.

Egyelőre 2 opció jött szóba:
 - Tisch Dávidnál
 - Dotroll-nál

Belinkeltem Dávidnak is ezt, remélhetőleg megjelenik, és több információt ad az általa felajánlott tárhelyről. Aggályként az merült fel, hogyha egy ember fér csak hozzá a tárhelyhez, akkor ha ő nem elérhető valami miatt, akkor az a release-elést akadályozza, illetve hosszú távon az egész oldal létét veszélyezteti.

**Comment by Pepita73** [comment]
Én arra szavazok, hogy Dotroll-nál.

Kérdés, hogy adnak-e esetleg 1-2 hétre kipróbálni egyet @inf3rno -nak? Ha nem, akkor kérek szépen egy issue-t, hogy takarítsam ki úgy az enyémet, hogy 7.2.x php-s lehessen.

**Comment by ghost** [comment]
@Pepita73 Egyelőre várjuk meg, hogy Dávid mit mond az általa felajánlott tárhelyről. Ha megoldható, hogy plusz egy ember tudjon kódot feltölteni, akkor az is jó lehet.

**Comment by ghost** [comment]
Esetleg csinálhatnánk ezt határidősre, hogyha nem jelentkezne x ideig, akkor dotroll lesz, aztán kész.

**Comment by Pepita73** [comment]
@inf3rno , a kérdésed miatt szavaztam, miszerint 

> Jó lenne dönteni a tárhelyről, hogy hol legyen.

Ez csak 1 szavazat, kíváncsi lennék mindenki véleményére.

Ezzel együtt határidőt is jó ötletnek tartom, határozd meg, mennyi legyen.

**Comment by Endyl** [comment]
Szerintem is mehet a határidős dolog.

**Comment by ghost** [comment]
Szerintem legyen összesen 1 hét, aztán lépjünk tovább. Aug 10. 18:15 körül küldtem levelet Dávidnak weblaboron keresztül, szóval aug 18-án legyen a végleges döntés erről, ha ti is beleegyeztek. Esetleg ha ismertek más elérhetőséget a weblaboros email-en keresztül Dávidhoz, akkor légyszi szóljatok neki!

**Comment by ghost** [comment]
Dotrollnál azt mondták, hogy van argon2. Mondjuk hogy utána néztek e az ügyfélszolgálatosok, arról fogalmam sincs. :D

**Comment by Pepita73** [comment]
Szerintem utána néztek. Legalábbis amikor szükségem volt rájuk, akkor nem beszéltek levegőbe - bár ez régen volt. 
Adnak esetleg teszt tárhelyet, vagy az enyémet kell befogni? 


Üdvözlettel:
Horváth Péter

(Mobilról)

**Comment by ghost** [comment]
@Pepita73 Nem kérdeztem, nem tartom fontosnak. Vagy van valami nagyon extra dolog, amit tesztelni akarunk?

**Comment by Pepita73** [comment]
@inf3rno semmi extra, csak gondoltam deploy-olni ott szeretnél, ahol lesz a cucc.

**Comment by ghost** [comment]
Most hogy így mondod, oda is be kéne szórni ezt dependency-nek. Viszont egyelőre még a teszt rendszert csinálom.

**Comment by tischdavid** [comment]
Sziasztok!
Bocsánat, hogy várnotok kellett rám! Ritkán olvasok így, szabadság alatt levelet.
A tárhely felajánlás az továbbra is áll, ha az segítség. Ez nem egy túl nagy virtuális szerver (talán 10 GB szabad helyünk van), úgyhogy a lehetőségek korlátozottak, de ha még így is segítség az ingyenes indulás, akkor részemről nincs akadálya.
Ha technikailag megvalósítható és nem gyengíti a rendszer biztonságát, akkor szívesen adok akárhány embernek hozzáférést ahhoz, amihez kell. Mondjátok meg, légyszi, hogy mihez kéne és hogyan (pl. egy adott könyvtárhoz FTP-n keresztül, vagy ilyesmi). (Sajnos nekem csak középhaladói szintű Linux ismereteim vannak, úgyhogy ha kérdés vagy igény van, akkor lehet, hogy szükségem lesz a támogatásotokra ennek megválaszolásában vagy megoldásában.)
Üdv:
Dávid

**Comment by ghost** [comment]
@tischdavid Szia! Köszi, hogy írtál! Engem az érdekelne, hogy milyen PHP verzió van, illetve ha nem szigorúan titkos, akkor hogy képzeljük el a tárhelyet? Bérlitek valahonnan, vagy saját szerver, illetve, hogy ezen a virtuális gépen csak mi leszünk, vagy esetleg zavarhatunk egy másik alkalmazást is, ha valamit elrontunk, pl megesszük a memóriát?

**Comment by tischdavid** [comment]
Sziasztok!
Mivel régebben írt kódokat futtatunk, ezért jelenleg 5.5.38-as PHP van a szerveren. A szerver egy virtuális szerver, ami a Rendszerinformatika Zrt. egy vasán került kialakításra; nem saját hardver. A virtuális gépen admin jogunk van.
Más, éles alkalmazások is futnak a szerveren, szóval konfigurálni csak nagy körültekintéssel szabad. Főleg, mivel a support lassú, úgyhogy ha elszúrunk valamit, azt - ha sürgős - nekünk is kell kijavítani.
Üdv: Dávid

**Comment by ghost** [comment]
@tischdavid 
Köszi! Hát elég rizikósnak hangzik a te részedről. :-) Kíváncsi vagyok a többiek mit gondolnak.

**Comment by Pepita73** [comment]
Azt gondolom, hogy Dotroll. :)

**Comment by ghost** [comment]
@Pepita73 Én nem szívesen veszélyeztetném Dávidék egyik alkalmazását sem. Szép gesztus, hogy felajánl tárhelyet a projektnek, de ez így szerintem túl rizikós az ő szempontjából, és valamennyire a mi szempontunkból is, mert gondolom felelősséget kell vállalni, ha valamit esetleg elrontunk. Remélem azért ebből nem lesz sértődés.

**Comment by Pepita73** [comment]
@Inf3rno, kérlek egyértelmű javaslatot is tegyél és @Endyl is. Én azt gondolom, hogy köszönöm szépen a lehetőséget Dávid, de szeretném inkább egy jó shared hostingon elindítani, aztán ha az kevés lesz, akkor egy komolyabb dolgon. 
(Egyébként elég "bátor" dolognak tartom komoly tudás vagy folyamatos support nélkül a VPS t, saját korlátaimat ismerve én biztos, hogy csak megfelelő support mellett csinálnám. )

Kód konvenciók között szerepelt az is, hogy ki használjuk a php 7 type és return type declaration lehetőséget is, de más okból se szeretnék 5.x alá menni. 
Azt gondolom, 2018 - ban minimum a 7.0 .
Eddigi tapasztalatom alapján jó shared hosting nak gondolom a Dotroll t, de ha valaki tud jobbat, nyitott vagyok rá. 

Remélem harag / sértődés nem születik ebből, szerintem mi, fejlesztők, tudunk logikusan gondolkodni. ;) 

Üdvözlettel:
Horváth Péter

(Mobilról)

**Comment by Endyl** [comment]
Egyetértek azokkal az aggályokkal, hogy nehogy valamit akár véletlenül is elpiszkáljunk más éles projektjeivel kapcsolatban, meg azzal is, hogy jobban járunk egy frissebb php verzióval.

Nem nagyon ismerem a hosting szolgáltatói piacot, úgyhogy ajánlani nem igazán tudok. Ha jó a dotroll, és még esetleg drusht is tudunk futtatni, hogy ne kelljen a GUI-n piszkálni élesítéskor, akkor részemről oké.

Egyébként hogyan fog történni ennek a finanszírozása?

**Comment by tischdavid** [comment]
Sziasztok!
Ha a "remélem, nem lesz harag/sértődés" aggályotok arra vonatkozott, hogy én nem haragszom/sértődöm-e meg, ha nem a mi tárhelyünket választjátok, akkor szeretnélek gyorsan megnyugtatni Titeket, hogy nem! :) Olyat válasszatok, ami hosszú távon is előre mutató! Az én felajánlásom relevanciáját egyedül az adta, hogy ingyen el lehetett volna indulni vele, de az elejétől kezdve féltem tőle, hogy a kissé elavult szoftver környezet nem lesz-e akadálya a dolognak.
Szóval a felajánlás áll, ha valami miatt nagyon szükségetek lenne rá, de remélem, hogy találtok jobb helyet!
Üdv: Dávid

**Comment by ghost** [comment]
@tischdavid Oké, köszönjük!

**Comment by ghost** [comment]
@Pepita73 Én is a dotrollra szavazok, azt hittem lejött a fentiek alapján. Azt hiszem akkor ezt lezárhatjuk. A finanszírozásnak szerintem nyissunk egy új issue-t.
