### ISSUE TITLE
Branch kezelés dokumentálása

### ISSUE THREAD

**Issue by Endyl** [Pepita73/webproghu_dev#32]
Ígértem, hogy írok valamit git flowról, meg branch kezelésről. Szerintetek elég nagyvonalakban leírni, hogy mit hogyan kellene, pár példa paranccsal? Mennyire kellhet ezt részletezni?

**Comment by ghost** [comment]
Én scenario-k köré szervezném a dolgot. Mondjuk ha van egy bug, vagy kitaláltatok egy új feature-t, akkor arra hogyan hozol létre új szálat, committelsz rá, mergelsz, pusholsz majd törlöd a már elkészült szálat, ha a pull request-et elfogadták. Ugyanígy a tracking-nél is van egy scenario, mert ott a tracking-nek is létrehozol egy külön szálat, és így tovább. Nekem elég címszavakban a scenario meg a commentelt kód, nem tudom más hogy van vele. Esetleg ha van valami spéci grafikus felület parancssor helyett, akkor annak a dokumentációjára egy link.

**Comment by Endyl** [comment]
[Ilyesmi formán](https://github.com/Pepita73/webproghu_dev/wiki/Branchek-kezel%C3%A9se) jó lesz?

Grafikus felülettel nem nagyon szoktam piszkálni a gitet, de a [GitKrakent](https://www.gitkraken.com/) sok helyen láttam, hogy dícsérik.

**Comment by ghost** [comment]
@Endyl Szerintem jó. Beleírtam, mert úgy rémlik idegen szavaknál kötőjel kell a toldalék elé, de lehet én tudom rosszul.

**Comment by Endyl** [comment]
[Nem kell mindenhol kötőjelezni.](https://helyesiras.mta.hu/helyesiras/default/akh12#215)

**Comment by ghost** [comment]
@Endyl Na legalább már ezt is tudom. Azt írja, csak akkor kell, ha szokatlan a vége a szónak. Volt benne egyébként néhány elírás is, azt is javítottam, szóval talán jobb az én verzióm. Úgy nézem revertelni nem lehet, legalábbis nem találom hol kéne. Csak a history-jét hozza fel.

**Comment by ghost** [comment]
No sikerült mégis revertelni (vagy revertölni?, valahol a kettő között mondják). Javítottam a feature elírását, illetve a directory-t dájrektörinek ejtik, szóval directory-re és nem -ra a helyes végződés. Na lapozzunk, ezt szerintem le lehet zárni, ha te is egyetértesz.

**Comment by Endyl** [comment]
Kicsit átírtam jobban általánosíthatóra. Majd még írok hozzá pár dolgot.

**Comment by ghost** [comment]
@Endyl Oké, ahogy gondolod. Az https://github.com/Pepita73/webproghu_dev/wiki/Branchek-kezel%C3%A9se#issue-t%C3%ADpus%C3%A1t%C3%B3l-f%C3%BCgg%C5%91-l%C3%A9p%C3%A9sek nekem nem világos, hogy miért került bele. Vagy az valami összefoglaló? Ha igen, akkor multiline code-al és commenttel talán jobb lenne. Ami még feltűnt, hogy `git flow feature checkout` van ebben, míg a másikban csak `git flow checkout`.

**Comment by Endyl** [comment]
Hozzáírtam, amit még szerettem volna. Remélem így már jobb az utolsó rész.

**Comment by ghost** [comment]
@Endyl 
Ja, sokkal jobb lett. A release branch kelleni fog, ha esetleg úgy döntünk, hogy kitoljuk a release folyamatát, hogy mindenki átnézhesse, aki akarja. Ami nincs tisztázva még benne, hogy a release bugfix-ei hogyan jutnak el a dev-be. Gondolom előbb merge-ölünk masterre, aztán onnan megy majd vissza dev-re, de ezt is jó lenne dokumentálni. A hotfix-nél is tisztázni kellene ugyanezt, illetve, hogy a git flow-os parancsok megcsinálják e helyettünk a dev-re juttatást, vagy azt nekünk kell külön.

**Comment by Endyl** [comment]
A release bugfixek és a hotfixek `develop`-ba való visszavezetése le van írva a [Branching modell](https://github.com/Pepita73/webproghu_dev/wiki/Branching-modell) oldalon.

Alapból megcsinálná a git flow ezeket a különféle `finish` parancsokkal. De direkt nem írtam róluk, mivel PR+review kell a merge-öléshez, így nem hiszem, hogy ezek működnének esetünkben. Illetve ezért írtam, hogy a befejezéshez PR kell. Szóval a `master -> develop` merge és a tagelés manuális feladat lesz.

**Comment by ghost** [comment]
Ok.
