### ISSUE TITLE
Inf3rno nem szerkesztő?!

### ISSUE THREAD

**Issue by Pepita73** [Pepita73/webproghu_dev#37]
http://weblabor.hu/forumok/temak/140703#comment-122721

@inf3rno , ezt nem igazán értem, nem kaptál meghívót / nem jó címed van WL-en?

**Comment by Pepita73** [comment]
Nem örülök neki, de kaptam választ WL-en.

http://weblabor.hu/forumok/temak/140703#comment-122725

**Comment by ghost** [comment]
Holnaptól el leszek nyaralni egy hétig. Nem tűntem el. :-)

**Comment by Pepita73** [comment]
Én is  (vasárnap éjjel megyünk), de terv szerint leszek néha gép előtt.  :)

Üdvözlettel:
Horváth Péter

(Mobilról)
