### ISSUE TITLE
Csatlakozás a fejlesztéshez

### ISSUE THREAD

**Issue by hidvegi-gabor** [Pepita73/webproghu_dev#39]
Egyelőre nem találtam más lehetőséget a csatlakozáshoz.

Gábor

**Comment by Pepita73** [comment]
@hidvegi-gabor , ez is jó, mert ahhoz, hogy contributor-ként hozzá tudjalak adni, a githubos username-re van szükségem.
Annyi a probléma, hogy ezt a username-et egy olyan csatornán kéne, hogy közöld, amelyikről tudom, hogy valóban az a személy, akire számítunk. :)

(Vagyis ezt a 22 óra "korú" account-ot bárki létrehozhatta, szeretném tudni, hogy tényleg Te vagy az. :) )

**Comment by Pepita73** [comment]
Pl. dobj egy emailt kérlek, hogy ez a Te account-od, olyan címről, amit ismerek.

**Comment by Pepita73** [comment]
Meghívást elküldtem, welcome @hidvegi-gabor  :)

**Comment by hidvegi-gabor** [comment]
Köszönöm, megvan. Amint lesz pár szabad percem, felírom a weblaborra, mit kell tenni a csatlakozáshoz.
