### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by Endyl** [Pepita73/webproghu_dev#4]
Hogyan megy a fejlesztés, milyen brancheket (vagy branching workflowt) használunk?

Mennyire legyen issue központú a dolog? Pl.: Egy jól definiált issue -> egy branch az erre vonatkozó kóddal -> PR?

Commit üzenetek magyarul vagy angolul? Ezen felül követünk valami formalizmust?

Issue-knak, pull requesteknek legyen formai követelménye? Code of conduct, contributing guildlines? (Lásd [Insights > community][community])

Egyéb?

---

- [x] #17 Branching
- [x] #19 Issue címkék
- [x] #28 Milestones

[community]: https://github.com/Pepita73/webproghu_dev/community

**Comment by Pepita73** [comment]
> Egy jól definiált issue -> egy branch az erre vonatkozó kóddal -> PR

Szerintem így.

branch név pl: f_4_workflow ha ez egy feature issue, b_4_workflow, ha ez bugfix. Szerintem így követhető lesz.
A "pepita-dev" és hasonló branch-eket kerülném.
Issue szerintem assign, aki megoldja (vegyük magunkra, ha elkezdjük).

> Commit üzenetek magyarul vagy angolul?

Nekem mindegy, ha csak magyarul tudó fejlesztők dolgoznak rajta, akkor akár magyar is lehet.

Többi kérdésedre válaszként egy kérdés: hogyan tudok olyan jogosultságot adni neked, hogy be tudd állítani, amiket szeretnél / megbeszélünk? :-D
Mint mondtam, github adminban nem vagyok otthon, szívesen lepasszolnám. :)

**Comment by Endyl** [comment]
Elvileg azt tudjuk kezelni, ami a Community részen van :) A settings fül az, amihez csak te férsz hozzá, és nem tudom, hogy ahhoz normál repónál tudsz-e jogosultságot adni. Bár szerintem ezek egyike sem olyan, amiben túl sűrűn kéne matatni. De akkor ha kialakult a megegyezés, és más nem előz meg, akkor beállítom én.

**Comment by Endyl** [comment]
1. Nekem az jött le, hogy elég, ha olyan hagyja jóvá, akinek van push joga. Majd meglátjuk a következő PR-nél.

2. Ha már van review folyamat, használjuk is. Több szem többet lát alapon jobb, ha valaki más is ellenőrzi a változtatásokat. Így még lejjebb szoríthatjuk a "nálam működik" típusú hibákat. Elvégre mindenki tévedhet :)

   Illetve így csökkenthető a [*code ownership* érzése][code-ownership].

[code-ownership]: https://medium.freecodecamp.org/why-code-ownership-sucks-and-you-should-never-work-somewhere-that-practices-it-b8fc1c694074

**Comment by inf3rno** [comment]
Talán nem tartozik annyira szorosan a workflow-hoz, de lesz majd valami automatizált build & deploy, vagy csak copy-paste-elünk majd az éles szerverre, ha kijövünk valami stabil verzióval?

**Comment by Endyl** [comment]
Szerintem amennyire lehet, automatizálni kéne azt is, mert a copy-paste-ben elég könnyű véletlenül hibázni. Ha nem is feltétlenül ide tartozik, de jó hogy előjött; kéne arra is issue, hogy valaki esetleg lecsaphasson rá :)

**Comment by Pepita73** [comment]
#9   :)

**Comment by Pepita73** [comment]
**Labels**
Felvettem az INFO labelt. Alábbiakban felsorolom, hogy én hogy látom a címkéket, majd ezt szerkesszük szerintem, ahogy csiszolódunk. 

- INFO: mindenkit érintő (folyamatos) infó. Egyszer talán bekerül wikibe.
- bug: ez egy hiba, javítsuk mielőbb.
- issue: elvégzendő feladat, rá lehet ugrani (amíg senki nem vette magára)
- question: kérdésem van. Ha kielégítő választ kaptam, leveszem róla (én, aki rátettem, mert én tudom, hogy nekem elég a válasz)

Többi magáért beszél, ha valamelyiket nem használjuk, törölhető szerintem.

**Comment by Endyl** [comment]
#9-ben felmerült, hogy [git flow][git-flow-branching]-t, vagy ahhoz hasonló branching modellt használnánk (minimum: fejlesztés develop és arról leágazó brancheken, működő, deployolható verzió pedig visszamerge-ölődik masterbe). Ha teljes egészében git flow szerint mennénk, akkor létezik ez az [eszköz][git-flow] is a mindenféle branching műveletek megkönnyítésére. De ennek ellenére mindenkinek át kéne nyálaznia a leírását, aki nem ismeri vagy nem tudja kívülről, hogy tudja mit-hova.

Részemről bármelyik OK.

[git-flow-branching]: https://nvie.com/posts/a-successful-git-branching-model/
[git-flow]: https://github.com/nvie/gitflow

**Comment by Endyl** [comment]
Leveszem a doc deeded-et, mert az információk más issuekba kerültek, amik dokumentálva lettek.

**Comment by ghost** [comment]
Szerintem ez elkészült, esetleg van még bármi egyéb?

**Comment by Endyl** [comment]
Egyelőre igen; ha lesz még workflow kérdés, majd nyitunk neki másikat.
