### ISSUE TITLE
files/ mappa tartalmának ignorálása

### ISSUE THREAD

**Issue by Endyl** [Pepita73/webproghu_dev#5]
**related:** #6 

A `sites/default/files` tartalmának a javát ki kéne szedni verziózás alól és alapból ignorálni mindent, mert itt van a twig, css, js, stb. cache, azokat meg nem akarjuk követni. Ha valamire mégis szükség van innen, akkor kivételt kell tenni rá.

**Comment by Pepita73** [comment]
Hajrá. :)

**Comment by Endyl** [comment]
Ha nem sürgős, akkor előbb majd próbáljuk meg/megpróbálom a composeres felállást belőni, abban ez meg van oldva. Ha az nem jön össze, vagy a többiek nem szeretnének composerezni, esetleg minél előbb szükség van erre, akkor persze megcsinálom :)

**Comment by Pepita73** [comment]
Ha szombat reggel - délelőtt ráérsz, akkor nyomhatnánk egy pair-programming-ot. :)
- volume legyen jó
- db link localhost
- composer
- gitignore
Drupal dolgaihoz Te sokkal jobban értesz, össze kéne beszéljünk szerintem és pikk-pakk megcsináljuk.

**Comment by Endyl** [comment]
Most hétvégén szerintem nem leszek gépközelben (legfeljebb vasárnap estefelé). De még hét közben igyekszem összerakni valamit a composerre.

**Comment by Pepita73** [comment]
[Innentől lesz más](https://github.com/Pepita73/webproghu_dev/blob/7f3bb460c0eb846e2f8cb4b941c9c0d24eded01f/apache/Dockerfile#L62)

Szerintem érdemes előtte (ezt a letöltést kitörölve) létrehozni a könyvtárakat, beállítani compose fájlban a volume-okat és megnézni, hogy kívül - belül műxik-e. 
Ha te nem tudsz kívülről új fájlt létrehozni, de amúgy a composeres install sikerül, már sokkal előrébb vagyunk.. (Akár azt is lehet, hogy ha te kész vagy, kiírod nekem, hogy milyen könyvtárakat kell kívülről is használni?)

Nem tudom, hogy néz ki a Drupal composerrel, a tuti az lenne, ha csak sites - themes - stb könyvtárakat kéne kitenni vendorból, többire max symlink, ha magától nem találja. Ez csak tipp.
