### ISSUE TITLE
Volume jogosultságok (linux)

### ISSUE THREAD

**Issue by Endyl** [Pepita73/webproghu_dev#6]
**related:** #5

Valaki tudja, hogyan lehet megoldani fenntartható módon azt, hogy ne kellejen a volume-ok jogosultságaival buherálni linuxon, hanem egy clone után működjön a dolog out-of-the-box módon, containeren kívül és belül?

**Comment by Pepita73** [comment]
Legyen issue, rá is tehetsz, hétvégén megyek rajta még1 kört. Biztos, hogy megoldható. 
Linux a konténer t jelenti? 


Üdvözlettel:
Horváth Péter

(Mobilról)

<div>-------- Eredeti üzenet --------</div><div>Feladó: Endyl <notifications@github.com> </div><div>Dátum:2018.07.30.  15:34  (GMT+01:00) </div><div>Címzett: Pepita73/webproghu_dev <webproghu_dev@noreply.github.com> </div><div>Másolatot kap: Subscribed <subscribed@noreply.github.com> </div><div>Tárgy: [Pepita73/webproghu_dev] Volume jogosultságok (linux) (#6) </div><div>
</div>Valaki tudja, hogyan lehet megoldani fenntartható módon azt, hogy ne kellejen a volume-ok jogosultságaival buherálni linuxon, hanem egy clone után működjön a dolog out-of-the-box módon, containeren kívül és belül?

**Comment by Pepita73** [comment]
Csináljuk együtt a gitignore-ral - db-vel, composer-rel együtt.

**Comment by Pepita73** [comment]
(Bocsi, hogy beleszerkesztettem, de legyen keresztlink.)

**Comment by Pepita73** [comment]
Egyelőre szerintem ez megoldva, ha netán felmerülne még ilyen, akkor nyissuk vissza vagy új issue.
settings.php-n kicsit "vitatkozott" (ha már volt, de újra composer install), de sikerült rávenni, hogy ésszel dolgozzon. :)
