### ISSUE TITLE
Sorvége karakterek normalizálása

### ISSUE THREAD

**Issue by Endyl** [Pepita73/webproghu_dev#7]
Mivel ellenvetés nem érkezett a #3-ban, kezdeményezném a sorvége karakterek normalizálást a [Dealing with line endings](https://help.github.com/articles/dealing-with-line-endings/) alapján. `.gitattributes` egyelőre:

```
# Set the default behavior, in case people don't have core.autocrlf set.
* text=auto

# Denote all files that are truly binary and should not be modified.
*.png binary
*.jpg binary
*.gif binary
```

Ellenvetés, jobb ötlet, kiegészítés esetén szóljatok!

**Comment by Pepita73** [comment]
Legalább push-ra kéne LF, de ez config:
`autocrlf = input`
De lehet, hogy ez is megoldja:
`text eol=lf`

**Comment by Endyl** [comment]
Nyilván config, de ha van `.gitattributes`, akkor mindegy, hogy kinek mi van helyileg beállítva, egységes lesz a repóban.
